Update the Backward Compatibility Service Level Agreement (SLA)
pytorch/rfcs pull request #35
Opened 2022-01-08 01:30 UTC by iseeyuan

Stack from [ghstack](https://github.com/ezyang/ghstack):
* (to be filled)

2022-01-10 15:35 UTC, cccclai commented on RFC-0017-PyTorch-Operator-Versioning.md
> +* PyTorch SLA will ensure that models developed using a cerntain version will be supported for *six months* from the version release date.
Is 6 months better or 180 days?

2022-01-10 18:37 UTC, raziel requested changes
Shouldn't we have a sub-section at the end of the proposal section that describes the new SLA? Rather than modifying the "History" section

2022-01-10 22:08 UTC, iseeyuan commented
> Shouldn't we have a sub-section at the end of the proposal section that describes the new SLA? Rather than modifying the "History" section

Good catch! Let me move to the proposal section and update the wording.

2022-01-18 20:16 UTC, mruberry approved these changes
LGTM!

2022-01-27 17:18 UTC, raziel commented
Thanks @iseeyuan 

Should we also call out as a goal/outcome that moving forward we're not having a difference between internal and OSS guarantees since they would be moving under the same SLA?

Also, update the Facebook / FB references :-)

2022-01-27 17:20 UTC, raziel approved these changes
Looks good, aside from the point I raised on internal vs oss

2022-01-27 17:23 UTC, iseeyuan commented
> Thanks @iseeyuan
> 
> Should we also call out as a goal/outcome that moving forward we're not having a difference between internal and OSS guarantees since they would be moving under the same SLA?
> 
> Also, update the Facebook / FB references :-)

Sounds good! Will call out the outcome, and update "Facebook". Thanks!

2022-01-27 18:08 UTC, merged